version: '3'
services:
  crm:
    build:
      context: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crm.rule=Host(`crm.clivattiadv.com.br`)"
      - "traefik.http.routers.crm.entrypoints=websecure"
      - "traefik.http.routers.crm.tls.certresolver=letsencrypt"
      - "traefik.http.services.crm.loadbalancer.server.port=80"
    networks:
      - NetRCadv

networks:
  NetRCadv:
    external: true
